import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { Util } from "../util.slint";
import { Label } from "../base/label.slint";
import { Divider } from "../base/divider.slint";

export component Footer inherits Rectangle {
    height: Theme.footer-height;

    VerticalLayout {
        Divider {}

        Rectangle {
            background: Theme.lighter-border-color;
            HorizontalLayout {
                alignment: space-between;
                spacing: Theme.spacing;
                padding-left: Theme.padding;
                padding-right: Theme.padding;

                Label {
                    text: Store.translator.btc-price + ": $" + Util.format-number-with-commas(Store.btc-info.price);
                }

                Label {
                    text: Store.translator.btc-per-byte-fee + ": " + Store.btc-info.byte-fee-slow + "/" + Store.btc-info.byte-fee-normal + "/" + Store.btc-info.byte-fee-fast;
                }

                Label {
                    text: Store.translator.update-time + ": " +  Store.btc-info.update-time;
                }
            }
        }
    }
}

