import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { Util } from "../util.slint";
import { Label } from "../base/label.slint";
import { IconBtn } from "../base/icon-btn.slint";

export component Header inherits Rectangle {
    height: Theme.header-height;
    background: Theme.lighter-border-color;

    HorizontalLayout {
        alignment: space-between;
        padding-left: Theme.padding * 2;
        padding-right: Theme.padding * 2;

        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                spacing: Theme.spacing * 2;

                IconBtn {
                    width: Theme.icon-size * 1.33;
                    icon-width: Theme.icon-size * 0.85;
                    icon: @image-url("../images/model.svg");
                    tip-pos: "bottom";
                    tip-text: Store.translator.tip-model;
                    clicked => { Store.current-panel = "model"; }
                }

                IconBtn {
                    width: Theme.icon-size * 1.33;
                    icon-width: Theme.icon-size * 0.85;
                    icon: @image-url("../images/voice.svg");
                    tip-pos: "bottom";
                    tip-text: Store.translator.tip-voice2text;
                    clicked => { Store.current-panel = "v2t"; }
                }

                IconBtn {
                    width: Theme.icon-size * 1.33;
                    icon-width: Theme.icon-size * 0.85;
                    icon: @image-url("../images/text-T.svg");
                    tip-pos: "bottom";
                    tip-text: Store.translator.tip-text2voice;
                    clicked => { Store.current-panel = "t2v"; }
                }

            }
        }

        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                spacing: Theme.spacing * 2;
                IconBtn {
                    width: Theme.icon-size * 1.33;
                    icon: @image-url("../images/setting-fill.svg");
                    tip-pos: "bottom";
                    tip-text: Store.translator.tip-setting;
                    clicked => {
                        Store.setting-dialog-config.show = true;
                    }
                }

                IconBtn {
                    width: Theme.icon-size * 1.33;
                    icon: @image-url("../images/help.svg");
                    tip-pos: "bottom";
                    tip-text: Store.translator.tip-help;
                    clicked => {
                        Store.help-dialog.show = true;
                    }
                }

                IconBtn {
                    width: Theme.icon-size * 1.33;
                    icon: @image-url("../images/info-dark.svg");
                    tip-pos: "bottom";
                    tip-text: Store.translator.tip-about;
                    clicked => {
                        Store.about-dialog.show = true;
                    }
                }
            }
        }
    }
}
