import { Theme } from "../theme.slint";
import { Logic } from "../logic.slint";
import { Store } from "../store.slint";
import { Header } from "./header.slint";
import { Bodyer } from "./bodyer/panel.slint";
import { Divider } from "../base/divider.slint";

export component Panel inherits Rectangle {
    in-out property model-type-index <=> bodyer.model-type-index;

    header := Header {
        x: 0; y: 0; z: 1;
    }

    VerticalLayout {
        padding: Theme.padding * 2;
        y: header.height;
        height: root.height - header.height;

        bodyer := Bodyer { }
    }

}

