import { Theme } from "./theme.slint";
import { Logic, Position } from "./logic.slint";
import { BaseLogic } from "./base/logic.slint";
import { Store, ModelItem } from "./store.slint";
import { Util } from "./util.slint";
import { Blanket } from "./base/blanket.slint";
import { Panel } from "./panel/panel.slint";
import { Message } from "./base/message.slint";
import { SettingDialog } from "./dialog/setting/dialog.slint";
import { AboutDialog } from "./dialog/about.slint";
import { HelpDialog } from "./dialog/help.slint";
import { OkCancelDialog } from "./dialog/ok-cancel.slint";

export component AppWindow inherits Window {
    default-font-size: Theme.default-font-size;
    default-font-family: Theme.default-font-family;
    width: Theme.default-width;
    height: Theme.default-height;
    background: Theme.base-background;
    icon: @image-url("./images/icon.png");
    forward-focus: fscope;
    title: "vtbox";

    in-out property model-type-index <=> panel.model-type-index;
    property<length> dialog-max-width: Math.min(root.width * 0.95, Theme.dialog-max-width);

    init => { }

    fscope := FocusScope {
        property <bool> is-ctrl-pressed: false;
        key-pressed(event) => {
            if (event.text == Key.Control) {
                is-ctrl-pressed = true;
            } else if (event.text == Key.Escape) {
                modal.hide();
            }

            if (is-ctrl-pressed) {
                if (event.text == ",") { }
            }
            accept
        }

        key-released(event) => {
            if (event.text == Key.Control) {
                is-ctrl-pressed = false;
            }
            accept
        }

        panel := Panel { }

        modal := Rectangle {
            function hide() {
                if (about-dialog.visible) {
                    Store.about-dialog.show = false;
                } else if (help-dialog.visible) {
                    Store.help-dialog.show = false;
                }
            }

            if setting-dialog.visible || oc-dialog.visible || about-dialog.visible || help-dialog.visible : low-modal := Blanket { }

            setting-dialog := SettingDialog {
                width: root.dialog-max-width;
            }

            oc-dialog := OkCancelDialog {}

            about-dialog := AboutDialog {
                width: root.dialog-max-width;
            }

            help-dialog := HelpDialog {
                width: root.dialog-max-width;
            }
        }

        msg := Message {
            x: root.width / 2 - self.width / 2;
            y: 50px;
            text: Store.message.text;
            type: Store.message.text-type;
            clicked => {
                Logic.copy-to-clipboard(self.text);
            }
        }
    }
}

export { Util, Logic, BaseLogic, Store, Position, ModelItem }
