import { Theme } from "./theme.slint";
import { Logic } from "./logic.slint";
import { Position } from "./logic.slint";
import { BaseLogic } from "./base/logic.slint";
import { Store } from "./store.slint";
import { AddressBookItem } from "./store.slint";
import { ActivityItem } from "./store.slint";
import { TxDetail } from "./store.slint";
import { Account } from "./store.slint";
import { Util } from "./util.slint";
import { Translator } from "./translator.slint";
import { Store } from "./store.slint";
import { MDItem } from "./base/data.slint";
import { Blanket } from "./base/blanket.slint";
import { Panel } from "./panel/panel.slint";
import { Message } from "./base/message.slint";
import { SettingDialog } from "./dialog/setting/dialog.slint";
import { TxDetailDialog } from "./dialog/tx-detail.slint";
import { PasswordDialog } from "./dialog/password.slint";
import { ChangePasswordDialog } from "./dialog/change-password.slint";
import { AddressBookAddItemDialog } from "./dialog/address-book-add-item.slint";
import { AddressBookQrcodeDialog } from "./dialog/address-book-qrcode.slint";
import { AddressBookDialog } from "./dialog/address-book.slint";
import { NewAccountDialog } from "./dialog/new-account.slint";
import { ShowMnemonicDialog } from "./dialog/show-mnemonic.slint";
import { AboutDialog } from "./dialog/about.slint";
import { HelpDialog } from "./dialog/help.slint";
import { OkCancelDialog } from "./dialog/ok-cancel.slint";
import { IconBtn } from "./base/icon-btn.slint";

export component AppWindow inherits Window {
    default-font-size: Theme.default-font-size;
    default-font-family: Theme.default-font-family;
    width: Theme.default-width;
    height: Theme.default-height;
    background: Theme.base-background;
    icon: @image-url("./images/icon.png");
    forward-focus: password-dialog;
    title: "Bitbox";

    property<length> dialog-max-width: Math.min(root.width * 0.95, Theme.dialog-max-width);

    in-out property new-account-dialog-type-index <=> new_account_dialog.type-index;
    in-out property receive-address <=> panel.receive-address;
    in-out property send-amount <=> panel.send-amount;
    in-out property feerate <=> panel.feerate;

    init => { }

    fscope := FocusScope {
        property <bool> is-ctrl-pressed: false;
        key-pressed(event) => {
            if (event.text == Key.Control) {
                is-ctrl-pressed = true;
            } else if (event.text == Key.Escape) {
                modal.hide();
            }

            if (is-ctrl-pressed) {
                if (event.text == ",") { }
            }
            accept
        }

        key-released(event) => {
            if (event.text == Key.Control) {
                is-ctrl-pressed = false;
            }
            accept
        }

        HorizontalLayout {
            panel := Panel { }
        }

        modal := Rectangle {
            function hide() {
                if (about-dialog.visible) {
                    Store.about-dialog.show = false;
                } else if (help-dialog.visible) {
                    Store.help-dialog.show = false;
                } else if (address-book-add-item-dialog.visible) {
                    Store.is-show-address-book-add-item-dialog = false;
                } else if (address-book-qrcode-dialog.visible) {
                    Store.is-show-address-book-qrcode-dialog = false;
                } else if (address-book-dialog.visible) {
                    Store.is-show-address-book-dialog = false;
                } else if (show-mnemonic-dialog.visible) {
                    Store.is-show-show-mnemonic-dialog = false;
                }
            }

            if address-book-add-item-dialog.visible || address-book-qrcode-dialog.visible || address-book-dialog.visible || setting-dialog.visible || oc-dialog.visible || about-dialog.visible || help-dialog.visible || password-dialog.visible || new-account-dialog.visible || show-mnemonic-dialog.visible || tx-detail-dialog.visible || change-password-dialog.visible : low-modal := Blanket { }

            address-book-add-item-dialog := AddressBookAddItemDialog {
                width: root.dialog-max-width;
            }

            address-book-qrcode-dialog := AddressBookQrcodeDialog {
                width: root.dialog-max-width;
            }

            address-book-dialog := AddressBookDialog {
                width: root.dialog-max-width;
            }

            password-dialog := PasswordDialog {}

            change-password-dialog := ChangePasswordDialog {}

            show-mnemonic-dialog := ShowMnemonicDialog {
                width: root.dialog-max-width;
            }

            new-account-dialog := NewAccountDialog {
                width: root.dialog-max-width;
            }

            tx-detail-dialog := TxDetailDialog {
                width: root.dialog-max-width;
            }

            setting-dialog := SettingDialog {
                width: root.dialog-max-width;
            }

            oc-dialog := OkCancelDialog {}

            about-dialog := AboutDialog {
                width: root.dialog-max-width;
            }

            help-dialog := HelpDialog {
                width: root.dialog-max-width;
            }
        }

        msg := Message {
            x: root.width / 2 - self.width / 2;
            y: 50px;
            text: Store.message.text;
            type: Store.message.text-type;
            clicked => {
                Logic.copy-to-clipboard(self.text);
            }
        }
    }
}

export { Util, Logic, BaseLogic, Store, Account, ActivityItem, AddressBookItem, TxDetail, Position }
