import { SettingDialogConfig, Store } from "./store.slint";

export struct Position {
    x: length,
    y: length,
}

export global Logic {
    callback hide-window();
    callback show-window();
    callback window-position() -> Position;
    callback update-position(int, int); // argument: position-x, position-y

    callback show-message(string, string);
    callback copy-to-clipboard(string);
    callback handle-ok-cancel-dialog(string, string);

    callback clean-cache();

    callback setting-cancel();
    callback setting-ok(SettingDialogConfig);

    callback switch-model-type(int); // argument: model-type-index
    callback remove-model(int, string); // argument: model-type-index, uuid
    callback refresh-model(int); // argument: model-type-index
    callback import-model(int); // argument: model-type-index
    callback download-model(int, string); // argument: model-type-index, uuid

    callback open-audio-file() -> string; // return: filepath
    callback start-v2t(string, string); // argument: model-name, audio-path


}

