import { Translator, Translation} from "./translator.slint";
import { MDItem } from "./base/data.slint";

export struct Account {
    uuid: string,
    name: string,
    address: string,
    network: string,
    balance-btc: string,
    balance-usd: string,
}

export struct ActivityItem {
    uuid: string,
    time: string,
    txid: string,
    operate: string,
    amount: string,
    fee: string,
    status: string,
}

export struct TxDetail {
    show: bool,
    network: string,
    send-address: string,
    receive-address: string,
    send-amount-btc: string,
    send-amount-usd: string,
    fee-amount-btc: string,
    fee-amount-usd: string,
    detail-hex: string,
    detail-raw: string,
}

export struct AddressBookItem {
    uuid: string,
    name: string,
    address: string,
}

export struct Password {
    show: bool,
    handle-type: string,
    handle-uuid: string,
}

export struct BtcInfo {
    price: string,
    byte-fee-slow: string,
    byte-fee-normal: string,
    byte-fee-fast: string,
    update-time: string,
}

export struct MessageItem {
    text: string,
    text-type: string,
}

export struct OkCancelDialogSetting {
    title-type: string,
    title-text: string,
    body-text: string,
    handle-type: string,
    handle-uuid: string,
}

export struct SettingUI {
    font-size: string,
    font-family: string,
    win-width: string,
    win-height: string,
    language: string,
}

export struct SettingAccount {
    max-feerate: string,
    max-fee-amount: string,
    max-send-amount: string,
    skip-utxo-amount: string,
}

export struct SettingProxy {
    enabled: bool,
    url: string,
    port: string,
}

export struct SettingDialogConfig {
    show: bool,
    ui: SettingUI,
    account: SettingAccount,
    proxy: SettingProxy,
}

export struct AboutDialog {
    show: bool,
    title: string,
    text: string,
    sponsor: string,
}

export global Store  {
    in-out property<Account> account: {
        balance-btc: "0",
        balance-usd: "0",
    };

    in-out property<bool> is-show-change-account-password-dialog: false;
    in-out property<bool> is-show-show-mnemonic-dialog: false;
    in-out property<bool> is-show-new-account-dialog: false;
    in-out property<string> account-mnemonic;

    in-out property<TxDetail> tx-detail-dialog: {
        show: false,
    };

    in-out property<bool> is-show-address-book-add-item-dialog: false;
    in-out property<bool> is-show-address-book-qrcode-dialog: false;
    in-out property<bool> is-show-address-book-dialog: false;
    in-out property<string> address-book-qrcode-address;
    in-out property<[AddressBookItem]> address-book-datas: [
        {
            uuid: "uuid-1",
            name: "name-1",
            address: "address-1",
        },
        {
            uuid: "uuid-2",
            name: "name-2wjifjwifjwif",
            address: "address-2wjfowefjwifjwifjwijfwijfwiefjwi",
        },
    ];

    in-out property<Password> password-dialog-config: {
        show: false,
    };

    in-out property<[ActivityItem]> activity-datas: [
        {
            uuid: "uuid-1",
            time: "12-10 23:45:12",
            txid: "31040072e777e124e120f6f157fdec1482062fb10055ba684e6dfc7b112f8241",
            operate: "send",
            amount: "0.12",
            fee: "0.001",
            status: "unconfirm",
        },
        {
            uuid: "uuid-2",
            time: "12-10 22:43:12",
            txid: "31040072e777e124e120f6f157fdec1482062fb10055ba684e6dfc7b112f8241",
            operate: "send",
            amount: "0.2",
            fee: "0.001",
            status: "confirm",
        }
    ];

    in-out property<BtcInfo> btc-info: {
        price: "0",
        byte-fee-slow: "0",
        byte-fee-normal: "0",
        byte-fee-fast: "0",
        update-time: "00:00:00",
    };

    in-out property<MessageItem> message;
    in-out property<OkCancelDialogSetting> ok-cancel-dialog-setting;

    in-out property<SettingDialogConfig> setting-dialog-config: {
        show: false,
        ui: {
            font-size: "18",
            font-family: "SourceHanSerifCN",
            win-width: "650",
            win-height: "550",
            language: "cn",
        },
        account: {
            max-feerate: "0",
            max-fee-amount: "0",
            max-send-amount: "0",
            skip-utxo-amount: "0",
        },
        proxy: {
            enabled: false,
            url: "127.0.0.1",
            port: "1080",
        }
    };

    in-out property<AboutDialog> about-dialog: {
        show: false,
        title: "Bitbox v0.0.1",
        text: "Based on Slint-UI. Copyright 2022-2030 The Heng30 Company Ltd. All rights reserved. The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.",
        sponsor: "0xf1199999751b1a3A74590adBf95401D19AB30014",
    };

    in-out property<Translation> translator: Translator.translation(setting-dialog-config.ui.language == "cn");

    in-out property<{show: bool, text-cn: string, text-en: string}> help-dialog: {
        show: false,
        text-cn:
              "配置和数据:\n"
            + "  1. 配置保存在~/.config/bitbox目录下。\n"
            + "  2. 数据保存在~/.local/share/bitbox目录下。\n"
            + "\n注意事项:\n"
            + "  1. 使用 blockstream API 进行交易广播，获取UTXO等链上信息。\n",

        text-en:
              "Configuration and data:\n"
            + "  1. Configuration is stored in the ~/.config/bitbox directory.\n"
            + "  2. Data is stored in the ~/.local/share/bitbox directory.\n"
            + "\nNote:\n"
            + "  1. Use blockstream API to broadcast transation, fetch UTXO and other on chain information.\n",
    };
}
