import { Translator, Translation} from "./translator.slint";

export struct ModelItem {
    uuid: string,
    name: string,
    size: string,
    status: string,
}

export struct MessageItem {
    text: string,
    text-type: string,
}

export struct OkCancelDialogSetting {
    title-type: string,
    title-text: string,
    body-text: string,
    handle-type: string,
    handle-uuid: string,
}

export struct SettingUI {
    font-size: string,
    font-family: string,
    win-width: string,
    win-height: string,
    language: string,
}

export struct SettingProxy {
    enabled: bool,
    url: string,
    port: string,
}

export struct SettingDialogConfig {
    show: bool,
    ui: SettingUI,
    proxy: SettingProxy,
}

export struct AboutDialog {
    show: bool,
    title: string,
    text: string,
    sponsor: string,
}

export global Store  {
    in-out property<string> current-panel: "v2t";

    in-out property <string> v2t-text;
    in-out property <[string]> v2t-models: [
        "ggml-tiny.bin",
        "ggml-base.bin",
        "ggml-small.bin",
        "ggml-medium.bin",
        "ggml-large.bin",
    ];

    in-out property<[ModelItem]> model-datas: [
        {
            uuid: "uuid-1",
            name: "model-1",
            size: "100M",
            status: "Downloaded",
        },
        {
            uuid: "uuid-2",
            name: "model-2",
            size: "200M",
            status: "Undownload",
        },
    ];

    in-out property<MessageItem> message;
    in-out property<OkCancelDialogSetting> ok-cancel-dialog-setting;

    in-out property<SettingDialogConfig> setting-dialog-config: {
        show: false,
        ui: {
            font-size: "18",
            font-family: "SourceHanSerifCN",
            win-width: "600",
            win-height: "500",
            language: "cn",
        },
        proxy: {
            enabled: false,
            url: "127.0.0.1",
            port: "1080",
        }
    };

    in-out property<AboutDialog> about-dialog: {
        show: false,
        title: "vtbox v0.0.1",
        text: "Based on Slint-UI. Copyright 2022-2030 The Heng30 Company Ltd. All rights reserved. The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.",
        sponsor: "0xf1199999751b1a3A74590adBf95401D19AB30014",
    };

    in-out property<Translation> translator: Translator.translation(setting-dialog-config.ui.language == "cn");

    in-out property<{show: bool, text-cn: string, text-en: string}> help-dialog: {
        show: false,
        text-cn:
              "配置和数据:\n"
            + "  1. 配置保存在~/.config/vtbox目录下。\n"
            + "  2. 数据保存在~/.local/share/vtbox目录下。\n",

        text-en:
              "Configuration and data:\n"
            + "  1. Configuration is stored in the ~/.config/vtbox directory.\n"
            + "  2. Data is stored in the ~/.local/share/vtbox directory.\n",
    };
}
