import { LineEdit } from "std-widgets.slint";
import { CDialog } from "../base/cdialog.slint";
import { Store } from "../store.slint";
import { Util } from "../util.slint";
import { Logic } from "../logic.slint";
import { Theme } from "../theme.slint";
import { Label } from "../base/label.slint";
import { IconBtn } from "../base/icon-btn.slint";

export component PasswordDialog inherits CDialog {
    visible: Store.password-dialog-config.show;
    title: Store.translator.password-dialog-title;
    forward-focus: password-lineedit;
    width: 400px;

    property<bool> is-show-password: false;

    HorizontalLayout {
        padding: Theme.padding * 2;
        spacing: Theme.spacing * 2;

        Label {
            text: Store.translator.password-dialog-password + ":";
        }

        password-lineedit := LineEdit {
            input-type: is-show-password ? text : password;
            accepted => { root.ok-clicked(); }
        }

        IconBtn {
            width: Theme.icon-size * 1.33;
            icon-width: Theme.icon-size;
            icon: is-show-password ? @image-url("../images/eye-close.svg") : @image-url("../images/eye.svg");
            tip-pos: "left";
            tip-text: is-show-password ? Store.translator.tip-hide : Store.translator.tip-show;
            clicked => {
                is-show-password = !is-show-password;
            }
        }
    }

    ok-clicked => {
        Store.password-dialog-config.show = false;

        Logic.handle-password-dialog(Store.password-dialog-config.handle-type, Store.password-dialog-config.handle-uuid, password-lineedit.text);
        password-lineedit.text = "";
    }

    cancel-clicked => {
        if (Store.password-dialog-config.handle-type == "logout") {
            Logic.show-message(Store.translator.please-login, "info");
            return;
        }

        password-lineedit.text = "";
        Store.password-dialog-config.show = false;
    }
}
