import { Theme } from "../../../theme.slint";
import { Store } from "../../../store.slint";
import { Logic } from "../../../logic.slint";
import { Util } from "../../../util.slint";
import { IconBtn } from "../../../base/icon-btn.slint";
import { CenterLayout } from "../../../base/center-layout.slint";
import { Label } from "../../../base/label.slint";

export component Receive inherits Rectangle {
    VerticalLayout {
        alignment: center;
        spacing: Theme.spacing * 2;

        CenterLayout {
            Image {
                width: 250px;
                height: self.width;
                source: Util.generate-qrcode(Store.account.address);
            }
        }

        CenterLayout {
            HorizontalLayout {
                spacing: Theme.spacing * 2;

                Label {
                    text: Store.account.address;
                    overflow: elide;
                    color: address-touch.has-hover ? Theme.link-text-color : Theme.primary-text-color;

                    address-touch := TouchArea {
                        mouse-cursor: self.has-hover ? pointer : default;
                        clicked => {
                            Util.open-url(
                                Util.blockstream-address-url(Store.account.network, Store.account.address));
                        }
                    }
                }


                IconBtn {
                    width: Theme.icon-size * 1.33;
                    icon-width: Theme.icon-size;
                    icon: @image-url("../../../images/copy.svg");
                    tip-pos: "top";
                    tip-text: Store.translator.tip-copy;
                    clicked => {
                        Logic.copy-to-clipboard(Store.account.address);
                    }
                }

            }
        }
    }
}
