import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { IconBtn } from "../../base/icon-btn.slint";
import { Divider } from "../../base/divider.slint";
import { Balance } from "./balance.slint";
import { Tool } from "./tool/panel.slint";

export component Bodyer inherits Rectangle {
    in-out property receive-address <=> tool.receive-address;
    in-out property send-amount <=> tool.send-amount;
    in-out property feerate <=> tool.feerate;

    VerticalLayout {
        spacing: Theme.spacing;

        Balance {}
        tool := Tool {}
    }
}

