import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { IconBtn } from "../../base/icon-btn.slint";
import { Divider } from "../../base/divider.slint";
import { Model } from "./model.slint";
import { V2T } from "./v2t.slint";
import { T2V } from "./t2v.slint";

export component Bodyer inherits Rectangle {
    Model {
        visible: Store.current-panel == "model";
    }

    V2T {
        visible: Store.current-panel == "v2t";
    }

    T2V {
        visible: Store.current-panel == "t2v";
    }
}

